'use strict';
module.exports = {
  up: async (queryInterface, _Sequelize) => queryInterface.bulkInsert('Cars',
    [
      {
        automaker: 'BMW',
        model: '320i',
        version: 'ACTIVE',
        image: 'http://img.estadao.com.br/jornal-do-carro/imagens/noticia/BMW_320I.JPG',
        info: 'https://www.carrosnaweb.com.br/fichadetalhe.asp?codigo=3342',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        automaker: 'AUDI',
        model: 'A3',
        version: 'TFSI',
        image: 'https://conteudo.imguol.com.br/c/entretenimento/2013/06/20/audi-a3-sedan-s-line-1371773379363_300x200.png',
        info: 'https://www.carrosnaweb.com.br/fichadetalhe.asp?codigo=3335',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        automaker: 'TOYOTA',
        model: 'COROLLA',
        version: 'ALTIS',
        image: 'http://4.bp.blogspot.com/-T00La-rTDMw/Ux6LdXXNbtI/AAAAAAABSDo/2AvQDrEnPck/s1600/Novo-Corolla-2015+(10).jpg',
        info: 'https://www.carrosnaweb.com.br/fichadetalhe.asp?codigo=1987',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        automaker: 'HONDA',
        model: 'CIVIC',
        version: 'LXS',
        image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSDNraC5JZmrFB5RhKLRFo5zvCu8woH69xLBA&usqp=CAU',
        info: 'https://www.carrosnaweb.com.br/fichadetalhe.asp?codigo=2162',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        automaker: 'VOLKSWAGEN',
        model: 'POLO',
        version: 'TSI',
        image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTiDKmDyiFUBxeGl--fCwpJG2nn-fDepCQYqg&usqp=CAU',
        info: 'https://www.carrosnaweb.com.br/fichadetalhe.asp?codigo=11749',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        automaker: 'FIAT',
        model: 'ARGO',
        version: 'HGT',
        image: 'https://cdn.motor1.com/images/mgl/jLOM6/s1/fiat-argo-hgt-avaliaco.jpg',
        info: 'https://www.carrosnaweb.com.br/fichadetalhe.asp?codigo=11700',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
    ], {}),

  down: async (queryInterface) => queryInterface.bulkDelete('Cars', null, {}),
};
